### ISSUE TITLE
Minestom Support

### ISSUE THREAD

**Issue by DinoMarlir** [mooziii/laboratory#13]
### Describe the new feature

-

### Why do you need this feature?

To use Minestom

**Comment by mooziii** [comment]
Minestom works different as far as i know e.g. mienstom doesn't provide downloads by themself so to use minestom you have to create your own jar, use the custom platform for this.

**Comment by DinoMarlir** [comment]
CloudNet has Minestom Support

**Comment by mooziii** [comment]
I think they use some third-party implementation of Minestom: https://minestom.net/implementations/
