### ISSUE TITLE
Dockerized Minecraft Servers like CloudNetV4

### ISSUE THREAD

**Issue by DinoMarlir** [mooziii/laboratory#15]
### Describe the new feature

You can start servers in Docker

### Why do you need this feature?

Idk it's nice XD

**Comment by mooziii** [comment]
There is a Docker Image available for laboratory. Due to it being very experimental, you need to build it yourself: [You can take a look at the official tutorial](https://laboratory.obsilabor.me/docs/chemicae/chemicae-in-docker)
