### ISSUE TITLE
the servers are displayed as running but the servers are not online

### ISSUE THREAD

**Issue by DinoMarlir** [mooziii/laboratory#21]
### Stacktrace

Paste a link to the stacktrace or the stacktrace itself here.

### How to reproduce

run the `laboratory list` command

### laboratory version

chemicae 0.5.22-dev

### Other

![grafik](https://user-images.githubusercontent.com/72864666/219724475-8213c1a1-614d-4f60-a75c-bb1213b8ed27.png)

**Comment by mooziii** [comment]
You need to have the chemicae server installed and running for this feature to work correctly as noted in the documentation [here](https://laboratory.obsilabor.me/docs/laboratory-basics/list-servers). If you need help during the chemicae installation, you can take a look at the [docs](https://laboratory.obsilabor.me/docs/chemicae/chemicae-in-docker)
